- name: nginx installing and starting
  hosts: frontend
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.package:
       name: nginx
       state: present
  - name: start nginx
    service:
      name: nginx
      state: started
      enabled: yes
  - name: debug
    debug:
      msg: "nginx installed and started successfully"