- name: nginx installing and starting
  hosts: frontend
  tasks:
  - name: installing nginx
    debug:
     msg: "installing nginx"
    ansible.builtin.package:
       name: nginx
       state: present
    debug:
      msg: " nginx installed"