- name: demo on variables vars_files
  hosts: presenthost
  connection: local
  vars_files: 
  - 05-course.yaml
  tasks:
  - name: text
    debug:
       msg: "Hi ,I am learing {{course}},trainer is {{trainer}}, duration is {{duration}}"
