- name: reading inputs
  hosts: presenthost
  connection: local
  vars_prompt:
   - name: username
     prompt: "Enter your name"
     private: "false"

   - name: password
     prompt: "Enter password"
     private: "true"
  
  tasks:
   - name: text
     debug:
       msg: "Username is {{username}}     paasword is {{password}}"
     