- name: even or odd
  hosts: localhost
  connection: local
  become: yes
  vars:
    num: 33
  tasks:
  - name: check even
    debug: 
      msg: "{{ num }} is even"
    when: num % 2 == 0
  - name: check odd
    debug: 
      msg: "{{ num }} is odd"
    when: num % 2 != 0
  
