[frontend]
172.31.21.112 course="html" #these are individual host variables
172.31.17.95 course="css"

[local]
localhost

[local:vars]
course="ansible"
trainer="siva kumar"
duration="150 hrs"

[frontend:vars]   #group variables
course="Ansible"
trainer="siva"
duration="12hrs"